### PR TITLE
Heavily refactor cookbook, tests, LWRP, more cow bell!

### PR DESCRIPTION
**Pull request by johnbellone**
This is a heavily refactored cookbook with more tests, more community cookbook usage, and more cowbell.

### CODE REVIEW

**Comment by johnbellone** [comment]
@schisamo Any thoughts?

**Comment by schisamo** [comment]
@johnbellone Would you like to take over maintenance and ownership of this cookbook? I no longer use ZNC.

**Comment by johnbellone** [comment]
@schisamo Sure!

**Comment by schisamo** [comment]
@johnbellone I'm getting this message when I try and transfer:

> johnbellone already has a repository in the schisamo/znc network

Delete your fork and I'm pretty sure I can transfer things over to you.

**Comment by johnbellone** [comment]
Done.

**Comment by schisamo** [comment]
@johnbellone OK I transferred ownership to you on GitHub AND SuperMarket.

**Comment by johnbellone** [comment]
Thanks!

**Pull request closed without merging**
